@startuml sequence_destroy
!theme plain
skinparam sequenceMessageAlign center

title Tile Destroy

participant ConsistencyTrendTileComponent as Comp
participant ChartJsLineAdapter as Adp
participant "chart.js Chart" as Chart

Comp -> Comp: ngOnDestroy
Comp -> Adp: destroy()
Adp -> Chart: chart.destroy()
Adp -> Adp: chart = undefined

@enduml
